# Generated by Django 4.0.6 on 2022-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True)),
                ('close_price', models.IntegerField(blank=True, null=True)),
                ('open_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('close_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('open', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('withdraw', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
