# Generated by Django 4.0.6 on 2022-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trade_open_alter_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wire',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
