# Generated by Django 4.0.6 on 2022-07-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_close_price_alter_trade_open_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='open_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
