# Generated by Django 4.0.6 on 2022-08-02 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_alter_trade_open_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='open_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 21, 19, 12, 975237)),
        ),
    ]
